# Generated by Django 3.2.9 on 2021-12-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barang', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaksi',
        ),
    ]
