# Generated by Django 3.2.9 on 2021-12-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0001_initial'),
        ('keranjang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemkeranjang',
            name='transaksi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaksi.transaksi'),
        ),
    ]
