# Generated by Django 3.2.9 on 2021-12-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_warung', '0003_barang_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('bintang', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='admin_warung.barang')),
            ],
        ),
    ]
