# Generated by Django 3.2.9 on 2021-12-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('idTransaksi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('statusTransaksi', models.CharField(max_length=100)),
                ('usernamePembeli', models.CharField(max_length=100)),
                ('caraPembayaran', models.CharField(max_length=100)),
            ],
        ),
    ]
