# Generated by Django 3.2.9 on 2021-12-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0002_alter_transaksi_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='totalPesanan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
