# Generated by Django 3.2.9 on 2021-12-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_transaksi', models.CharField(max_length=200)),
                ('num_users', models.IntegerField()),
            ],
        ),
    ]
