# Generated by Django 3.2.9 on 2021-12-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.PositiveIntegerField(blank=True, null=True)),
                ('stok', models.PositiveIntegerField(blank=True, null=True)),
                ('terjual', models.PositiveIntegerField(blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
