# Generated by Django 3.2.9 on 2021-12-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='id_barang',
        ),
    ]
