# Generated by Django 3.2.9 on 2021-12-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='id_barang',
        ),
        migrations.AddField(
            model_name='barang',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='harga',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='stok',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='terjual',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
