# Generated by Django 3.2.9 on 2021-12-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warung', '0002_auto_20211205_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
