# Generated by Django 3.2.9 on 2021-12-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warung', '0003_remove_barang_id_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
