# Generated by Django 3.2.9 on 2021-12-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_warung', '0004_barang_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='image',
            new_name='image_url',
        ),
    ]
